# Change these first
owner: formsure # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://formsure.co
  - name: Formsure API
    url: https://api.formsure.co
    expectedStatusCodes:
     - 404
  - name: Formsure Dashboard
    url: https://app.formsure.co
  - name: Documentation
    url: https://docs.formsure.co


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.formsure.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars0.githubusercontent.com/u/75302021?s=44&v=5
  logoHref: https://formsure.co
  favicon: https://formsure.co/assets/favicons/favicon-16x16.png?v=rMBOpxyMqM
  name: "Formsure"
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: ""
  
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
