# Change these first
owner: formsure # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Website
    url: https://formsure.co
  - name: API
    url: https://api.formsure.co
    expectedStatusCodes:
     - 404
  - name: Dashboard
    url: https://app.formsure.co


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.formsure.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://formsure.co/assets/img/logo.svg
  name: Formsure
  introTitle: "Create surveys, polls, and quizzes and get feedback at ease"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
